Check for pipeline errors, terminate if any

diff --git a/todoer b/todoer
--- a/todoer
+++ b/todoer
@@ -2,8 +2,19 @@
 
 repo=$1
 todo_pattern=TODO
+pipeline_erros=()
 
 # TODO handle relative paths in proper way
+
+check_for_pipeline_error() {
+    for i in ${PIPESTATUS[*]}; do
+        if [ $i != 0 ]; then
+            echo "There was an error in the pipeline"
+            echo "Terminating execution"
+            exit 1
+        fi
+    done
+}
 
 find_files_with_todos() {
     ack -l $todo_pattern
@@ -11,6 +22,7 @@ find_files_with_todos() {
 
 find_todo_line_nums() {
     cat $1 | xargs grep -n $todo_pattern | cut -d : -f $2 > ../$3
+    check_for_pipeline_error
 }
 
 create_tmp_files() {
@@ -41,6 +53,7 @@ get_todo_dates() {
         | sed 's/\(^.*\)\((.*....-..-..\.*)\)\(.*$\)/\2/g' \
         | sed 's/.*\(....-..-..\).*/\1/g' \
         | grep -v '^.*[a-zA-Z].*'
+    check_for_pipeline_error
 }
 
 duration_in_days() {
@@ -64,6 +77,7 @@ years_old() {
 
 summarise() {
     years_old | sort | uniq -c | sort -nr | sed 's/\(.*\) \(.*\)/\1 - \2 years/g'
+    check_for_pipeline_error
 }
 
 doit() {
